### ISSUE TITLE
@conda-forge-admin pleas add automerge

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/google-cloud-pubsub-feedstock#44]

**Comment by hmaarrfk** [comment]
@conda-forge-admin please add automerge

**Comment by xylar** [comment]
I think this is a bad idea because dependencies do evolve on this feedstock.

**Comment by xylar** [comment]
See, for example:
https://github.com/googleapis/python-pubsub/compare/v2.13.5...v2.13.6#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

**Comment by tpdownes** [comment]
I agree that this is a bad idea for the stated reason. https://github.com/conda-forge/google-cloud-pubsub-feedstock/pull/43#pullrequestreview-1071188882
